### ISSUE TITLE
categoryBitMask

### ISSUE THREAD

**Issue by seivan** [zaycev/bevy-magic-light-2d#58]
Is it possible to add a `categoryBitMask` to define what gets lit up and not? 
This would help to prevent light leaving an enclosed room. 

So a light component would define the mask and the surrounding sprites would update their masks to match.

> To determine whether this sprite is lit by a light node, the sprite’s lightingBitMask property is tested against the light’s `categoryBitMask]`  property by performing a logical AND operation. If the comparison results in a nonzero value, the sprite is lit by this light.

They also have  `shadowedBitMask` and `shadowCastBitMask`:

This feature is supported by SpriteKit by Apple. 
[SpriteKit](https://developer.apple.com/documentation/spritekit/skspritenode/1519637-lightingbitmask)

**Comment by zaycev** [comment]
@seivan I'm going to keep this issue open for now, but I think this would be a little bit difficult to implement at the moment.

> This would help to prevent light leaving an enclosed room.

Can you achieve this with adding occludes surrounding your room or maybe I miss something. In Krypta example the light is not escaping the room because each wall block has an occluder component.

**Comment by seivan** [comment]
@zaycev Right, so what I asking about is the idea that you can match occluders with specific lights. But occluders solves the current problem for now, thanks!
