### ISSUE TITLE
regression: lights now trail movement

### ISSUE THREAD

**Issue by CarsonBurke** [zaycev/bevy-magic-light-2d#64]
I migrated my project from bevy 0.13 -> 0.14.1, and coincidingly updated bevy-magic-light-2d. With no other changes besides minor, unrelated migration changes, lights now trail movement similar to the effect of zooming that has persisted through all magic light versions. Here is a video below; looking closely you can see the lights trail the large grey circles and red circles, which again, is not behaviour experienced in previous versions.

https://github.com/user-attachments/assets/1b0f0361-b10f-42a3-b3e2-ece78864e28b

I believe, according to my understanding of what I've heard, that this is related to the lighting being updated every 5 ticks. Not only does this affect camera zoom, but is now effecting light movement.

**Comment by tigerplush** [comment]
@CarsonBurke could you record the same with bevy 0.13 and magic_light 0.7 ? My understanding is, that it should work just the same. The light is averaged over the last 8 frames (as specified by the `reservoir_size` of the `LightPassParams`), so this should have been visibile in 0.7 too.

You can see it in the krypta example when moving the mouse: krypta example has a default reservoir size of 16, if you set that to 1 or 2, the trail is gone (or not perceptible?) 
The lights would flicker then (because there is some randomness applied to have them flicker), which could be eliminated by setting the jitter_intensity and jitter_translation to 0.0, but if you don't have jitter set on your Omnilight component, you might get away by reduicing the reservoir size

[edit] I tried the krypta example with v0.7 and the same trailing exists there too.

**Comment by CarsonBurke** [comment]
You are correct, this is not actually a regression. Apologies

**Comment by tigerplush** [comment]
I'm reopening this issue, because it is actually a regression.
During update to bevy 0.14.1 we dismissed the vviz because we didn't read the migration guide carefully enough

**Comment by CarsonBurke** [comment]
> I'm reopening this issue, because it is actually a regression. During update to bevy 0.14.1 we dismissed the vviz because we didn't read the migration guide carefully enough

I believe this is incorrect. I don't think this is a regression. I think, as you mentioned to me before, that it was hard to tell that lights were trailing in previous versions due to higher FPS. Revisiting my 0.13 benchmarks, it is apparent that lights did indeed trail in that version as well.
